import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navigation from "./components/Navigation";

// const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "COCVAC Reports",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
